CREATE TABLE IF NOT EXISTS user (
  tgID INT PRIMARY KEY,
  address TEXT,
  ghusername TEXT,
  tgusername TEXT,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  admin BOOLEAN NOT NULL DEFAULT FALSE,
  access TEXT NOT NULL DEFAULT 'pull'
);

CREATE TABLE IF NOT EXISTS level (
  name TEXT PRIMARY KEY,
  repos TEXT,
  user TEXT,
  lvl INT NOT NULL CHECK(lvl >= 0) DEFAULT 0,
  FOREIGN KEY (user) REFERENCES user (tgID) ON DELETE CASCADE ON UPDATE CASCADE
  FOREIGN KEY (repos) REFERENCES repos (name) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS repos (
  name TEXT PRIMARY KEY,
  repos TEXT,
  user TEXT,
  lvl INT NOT NULL CHECK(lvl >= 0) DEFAULT 0,
  FOREIGN KEY (user) REFERENCES user (tgID) ON DELETE CASCADE ON UPDATE CASCADE
);
